"""S4-C implementation runner.

Consumes only a plan generated by the frozen protocol authority. The runner:
1. executes the real Rust selector and independent Python parity before CSP bytes;
2. measures the exact 9-target / 106-base-pair ChunkShift quality table;
3. if quality is correct, executes the seven frozen paired timing rounds.

Scientific failures are retained as evidence and do not get retried inside a run.
"""

import argparse
import importlib
import json
import os
from pathlib import Path
import shutil
import sys
import tempfile
import time

TOOLS = Path(__file__).resolve().parent
sys.path.insert(0, str(TOOLS))

import selector_s4_runner as s4  # noqa: E402

PROTOCOL_SHA = "9ec28a0022651bb7416871089b0bcc4edd3454b8"
CONSUMER_SHA = "74bb301b6d8ecc52cf0bc0e00d86fa174093d91b"
PLAN_SCHEMA = "delsk.chunkshift-s4-confirm.plan.v1"
SELECTION_SCHEMA = "delsk.chunkshift-s4-confirm.selection.v1"
COST_SCHEMA = "delsk.chunkshift-s4-confirm.rust-cost.v1"
TIMING_SCHEMA = "delsk.chunkshift-s4-confirm.timing.v1"
RUN_SCHEMA = "delsk.chunkshift-s4-confirm.run.v1"
ROUND_ORDERS = ("P-D", "D-P", "P-D", "D-P", "P-D", "D-P", "P-D")


class ConfirmRunnerError(Exception):
    pass


def check(ok, message):
    if not ok:
        raise ConfirmRunnerError(message)


def canonical(value):
    return json.dumps(value, sort_keys=True, separators=(",", ":")) + "\n"


def load_plan(path):
    doc = json.loads(Path(path).read_text(encoding="utf-8"))
    check(doc.get("schema") == PLAN_SCHEMA, "foreign S4-C plan")
    check(doc.get("protocol_authority") == PROTOCOL_SHA, "protocol authority drift")
    check(doc.get("consumer_commit") == CONSUMER_SHA, "consumer drift")
    check(doc.get("split") == "evaluation" and doc.get("family") == "bzip2", "holdout population drift")
    check(doc.get("k") == 2 and doc.get("abstention_level") == 0, "selector decision drift")
    targets = doc.get("targets")
    check(isinstance(targets, list) and len(targets) == 9, "target count drift")
    check(sum(len(t.get("bases", [])) for t in targets) == 106, "pair count drift")
    check(doc.get("expected_measurements") == 115, "measurement count drift")
    check(doc.get("round_orders") == list(ROUND_ORDERS), "round order drift")
    return doc


def _hex_text(value):
    return "-" if value is None else str(value).encode("utf-8").hex()


def driver_input(plan, path):
    rows = []
    for target in sorted(plan["targets"], key=lambda t: t["target_occurrence_id"]):
        tid = target["target_occurrence_id"]
        for kind, meta in [("T", target["target"]), *[("B", b) for b in target["bases"]]]:
            check(isinstance(meta.get("object_id"), str) and len(meta["object_id"]) == 64, "object id drift")
            check(isinstance(meta.get("bytes"), int) and meta["bytes"] >= 0, "object bytes drift")
            offset = "-" if meta.get("offset") is None else str(meta["offset"])
            rows.append("\t".join([
                kind,
                tid,
                meta["object_id"],
                str(meta["bytes"]),
                str(meta["version_rank"]),
                offset,
                _hex_text(meta.get("path")),
                _hex_text(meta.get("line")),
            ]))
    Path(path).write_text("\n".join(rows) + "\n", encoding="utf-8")


def unique_objects(plan):
    out = {}
    for target in plan["targets"]:
        for meta in [target["target"], *target["bases"]]:
            oid = meta["object_id"]
            if oid in out:
                check(out[oid]["bytes"] == meta["bytes"], f"object size drift: {oid}")
            else:
                out[oid] = meta
    return dict(sorted(out.items()))


def load_authority_selector(protocol_root):
    tools = Path(protocol_root) / ".work" / "tools"
    check(tools.is_dir(), "protocol tools missing")
    sys.path.insert(0, str(tools))
    return importlib.import_module("simple_selector"), importlib.import_module("baselines")


def python_selection(plan, store, protocol_root):
    ss, _ = load_authority_selector(protocol_root)
    objects = unique_objects(plan)
    descriptors = {}
    for oid in objects:
        data = (Path(store) / oid).read_bytes()
        check(s4.file_sha256(Path(store) / oid) == oid, f"object integrity failure: {oid}")
        descriptors[oid] = ss.descriptor(data)
    out = {}
    for target in plan["targets"]:
        out[target["target_occurrence_id"]] = ss.select(target["target"], target["bases"], descriptors, 2)
    return out


def run_rust_driver(binary, store, tsv, out):
    completed, wall, cpu = s4.run_process([str(binary), str(store), str(tsv), str(out)])
    check(completed.returncode == 0, f"Rust selector driver failed: {completed.stderr[-500:]}")
    doc = json.loads(Path(out).read_text(encoding="utf-8"))
    check(doc.get("schema") == "delsk.chunkshift-s4-confirm.rust-driver.v1", "Rust driver schema drift")
    check(doc.get("objects") > 0 and doc.get("object_bytes_scanned") > 0, "Rust driver empty population")
    check(len(doc.get("query_ns", [])) == 9, "Rust query vector drift")
    check(len(doc.get("query_round_ns", [])) == 7, "Rust timing query vector drift")
    check(len(doc.get("selections", [])) == 9, "Rust selection population drift")
    doc["driver_process_wall_ns"] = wall
    doc["driver_process_cpu_ns"] = cpu
    return doc


def selection_record(rust_doc, python_ids):
    rows = []
    seen = set()
    for row in rust_doc["selections"]:
        tid = row["target_occurrence_id"]
        check(tid not in seen and tid in python_ids, "Rust selection target drift")
        seen.add(tid)
        rows.append({
            "target_occurrence_id": tid,
            "rust_k2": row["rust_k2"],
            "python_k2": python_ids[tid],
        })
    check(seen == set(python_ids), "selection target set incomplete")
    rows.sort(key=lambda row: row["target_occurrence_id"])
    return {
        "schema": SELECTION_SCHEMA,
        "selector": "delsk.simple-selector.v1",
        "k": 2,
        "targets": rows,
    }


def rust_cost_record(rust_doc):
    return {
        "schema": COST_SCHEMA,
        "objects": rust_doc["objects"],
        "object_bytes_scanned": rust_doc["object_bytes_scanned"],
        "descriptor_bytes": rust_doc["descriptor_bytes"],
        "descriptor_wall_ns": rust_doc["descriptor_wall_ns"],
        "descriptor_cpu_ns": rust_doc["descriptor_cpu_ns"],
        "catalog_wall_ns": rust_doc["catalog_wall_ns"],
        "catalog_cpu_ns": rust_doc["catalog_cpu_ns"],
        "index_bytes": rust_doc["index_bytes"],
        "query_ns": rust_doc["query_ns"],
        "driver_process_wall_ns": rust_doc["driver_process_wall_ns"],
        "driver_process_cpu_ns": rust_doc["driver_process_cpu_ns"],
    }


def _target_adapter(target):
    return {
        "target_occurrence_id": target["target_occurrence_id"],
        "target_object_id": target["target"]["object_id"],
    }


def create_manifests(plan, store, cli, work):
    manifests = {}
    rows = []
    manifest_dir = work / "manifests"
    for oid in unique_objects(plan):
        path = Path(store) / oid
        s4.verify_object(path, oid)
        record, manifest = s4.create_manifest(cli, path, oid, manifest_dir)
        manifests[oid] = (record, manifest)
        rows.append(record)
    rows.sort(key=lambda row: row["object_id"])
    return manifests, rows


def quality_table(plan, store, cli, manifests, work):
    rows = []
    for target in sorted(plan["targets"], key=lambda t: t["target_occurrence_id"]):
        adapted = _target_adapter(target)
        rows.append(s4.measure_pair(cli, adapted, None, Path(store), manifests, work))
        for base in target["bases"]:
            rows.append(s4.measure_pair(cli, adapted, base["object_id"], Path(store), manifests, work))
    rows.sort(key=lambda row: (row["target_occurrence_id"], row["base_object_id"] or ""))
    check(len(rows) == 115, "quality row count drift")
    check(len({(r["target_occurrence_id"], r["base_object_id"]) for r in rows}) == 115, "duplicate quality pair")
    return rows


def _create_patch(cli, adapted, base_id, store, manifests, work, stem):
    target_id = adapted["target_object_id"]
    target_manifest = manifests[target_id][1]
    target_manifest_id = manifests[target_id][0]["manifest_id"]
    base_path = base_manifest = base_manifest_id = None
    if base_id is not None:
        base_path = Path(store) / base_id
        base_manifest = manifests[base_id][1]
        base_manifest_id = manifests[base_id][0]["manifest_id"]

    patch = work / f"{stem}.csp"
    args = [
        "dotnet", str(cli), "patch", "create",
        "--target-manifest", str(target_manifest),
        "--target", str(Path(store) / target_id),
        "-o", str(patch),
    ]
    if base_id is not None:
        args += ["--base-manifest", str(base_manifest), "--base", str(base_path)]

    completed, wall, cpu = s4.run_process(args)
    fields = s4.parse_kv(completed.stdout)
    check(completed.returncode == 0 and patch.is_file() and not patch.is_symlink(), "timing patch create failed")
    patch_bytes = patch.stat().st_size
    check(patch_bytes > 0 and fields.get("target-manifest-id") == target_manifest_id, "timing target binding failed")
    check(fields.get("patch-bytes") == str(patch_bytes), "timing patch byte report drift")
    if base_id is None:
        check("base-manifest-id" not in fields, "standalone timing patch has a base")
    else:
        check(fields.get("base-manifest-id") == base_manifest_id, "timing base binding failed")
    return {
        "base_id": base_id,
        "path": patch,
        "bytes": patch_bytes,
        "create_wall_ns": wall,
        "create_cpu_ns": cpu,
    }


def _apply_chosen(cli, adapted, candidate, store, manifests, work, stem):
    output = work / f"{stem}.out"
    args = ["dotnet", str(cli), "patch", "apply", str(candidate["path"]), "-o", str(output)]
    if candidate["base_id"] is not None:
        base = candidate["base_id"]
        args += ["--base-manifest", str(manifests[base][1]), "--base", str(Path(store) / base)]
    completed, wall, cpu = s4.run_process(args)
    check(completed.returncode == 0 and output.is_file() and not output.is_symlink(), "timing apply failed")
    check(s4.file_sha256(output) == adapted["target_object_id"], "timing reconstruction mismatch")
    output.unlink(missing_ok=True)
    return wall, cpu


def timed_lane(plan, selected, lane, cli, store, manifests, work, round_index, selector_query_ns):
    create_wall = create_cpu = apply_wall = apply_cpu = 0
    for target in sorted(plan["targets"], key=lambda t: t["target_occurrence_id"]):
        tid = target["target_occurrence_id"]
        if lane == "previous1":
            base_ids = target["previous1"]
        else:
            base_ids = selected[tid]
        adapted = _target_adapter(target)
        candidates = []
        for ordinal, base_id in enumerate([None, *base_ids]):
            stem = f"r{round_index}-{lane}-{tid[:12]}-{ordinal}"
            candidate = _create_patch(cli, adapted, base_id, store, manifests, work, stem)
            create_wall += candidate["create_wall_ns"]
            create_cpu += candidate["create_cpu_ns"]
            candidates.append(candidate)
        chosen = min(candidates, key=lambda row: (row["bytes"], row["base_id"] or ""))
        wall, cpu = _apply_chosen(cli, adapted, chosen, store, manifests, work, f"r{round_index}-{lane}-{tid[:12]}")
        apply_wall += wall
        apply_cpu += cpu
        for candidate in candidates:
            candidate["path"].unlink(missing_ok=True)
    return {
        "selector_query_ns": selector_query_ns,
        "create_wall_ns": create_wall,
        "create_cpu_ns": create_cpu,
        "apply_wall_ns": apply_wall,
        "apply_cpu_ns": apply_cpu,
    }


def previous_query_ns(plan, baselines):
    started = time.perf_counter_ns()
    for target in plan["targets"]:
        got = baselines.rank_previous_version({"target": target["target"], "bases": target["bases"]})[:1]
        check(got == target["previous1"], "previous1 plan drift")
    return time.perf_counter_ns() - started


def timing_rounds(plan, rust_round_doc, selected, cli, store, manifests, work, protocol_root):
    _, baselines = load_authority_selector(protocol_root)
    check(len(rust_round_doc["query_round_ns"]) == 7, "Rust round vector drift")
    rounds = []
    for i, order in enumerate(ROUND_ORDERS):
        p_query = previous_query_ns(plan, baselines)
        d_query = rust_round_doc["query_round_ns"][i]
        lanes = {}
        for lane in ("previous1", "delsk2") if order == "P-D" else ("delsk2", "previous1"):
            lanes[lane] = timed_lane(
                plan,
                selected,
                lane,
                cli,
                store,
                manifests,
                work,
                i,
                p_query if lane == "previous1" else d_query,
            )
        rounds.append({"order": order, **lanes})
    return {"schema": TIMING_SCHEMA, "rounds": rounds}


def write_json(path, value):
    Path(path).write_text(json.dumps(value, indent=2, sort_keys=True) + "\n", encoding="utf-8")


def run(args):
    plan = load_plan(args.plan)
    protocol_sha = args.protocol_authority.lower()
    implementation_sha = args.implementation_sha.lower()
    check(protocol_sha == PROTOCOL_SHA, "protocol authority differs from frozen S4-C authority")
    check(s4.is_hex(implementation_sha, 40), "invalid implementation SHA")

    cli = Path(args.chunkshift_dll)
    rust_binary = Path(args.rust_binary)
    store = Path(args.store)
    check(cli.is_file() and not cli.is_symlink(), "ChunkShift CLI missing")
    check(rust_binary.is_file() and not rust_binary.is_symlink(), "Rust confirmation driver missing")

    out = Path(args.out_dir)
    out.mkdir(parents=True, exist_ok=True)
    work = Path(tempfile.mkdtemp(prefix=f"s4c-{args.repeat.lower()}-"))
    try:
        tsv = work / "driver.tsv"
        rust_json = work / "rust.json"
        driver_input(plan, tsv)
        rust_doc = run_rust_driver(rust_binary, store, tsv, rust_json)
        python_ids = python_selection(plan, store, args.protocol_root)
        selection = selection_record(rust_doc, python_ids)
        write_json(out / "selection.json", selection)
        write_json(out / "rust-cost.json", rust_cost_record(rust_doc))

        parity_ok = all(row["rust_k2"] == row["python_k2"] for row in selection["targets"])
        rows = []
        manifest_rows = []
        timing = {"schema": TIMING_SCHEMA, "rounds": []}
        science_state = "PARITY_FAILED"

        if parity_ok:
            manifests, manifest_rows = create_manifests(plan, store, cli, work)
            rows = quality_table(plan, store, cli, manifests, work)
            if all(row["status"] == "ok" for row in rows):
                second_rust = run_rust_driver(rust_binary, store, tsv, work / "rust-timing.json")
                second_selected = {r["target_occurrence_id"]: r["rust_k2"] for r in second_rust["selections"]}
                first_selected = {r["target_occurrence_id"]: r["rust_k2"] for r in selection["targets"]}
                check(second_selected == first_selected, "Rust K2 selection changed before timing")
                timing = timing_rounds(
                    plan, second_rust, first_selected, cli, store, manifests, work, args.protocol_root
                )
                science_state = "COMPLETE"
            else:
                science_state = "QUALITY_PAIR_FAILED"

        s4.write_jsonl(out / "measurements.jsonl", rows)
        s4.write_jsonl(out / "manifests.jsonl", manifest_rows)
        write_json(out / "timing.json", timing)

        run_record = {
            "schema": RUN_SCHEMA,
            "repeat": args.repeat,
            "protocol_authority": protocol_sha,
            "implementation_sha": implementation_sha,
            "head_sha": os.environ.get("GITHUB_SHA"),
            "workflow_sha": os.environ.get("GITHUB_WORKFLOW_SHA"),
            "ref": os.environ.get("GITHUB_REF"),
            "event": os.environ.get("GITHUB_EVENT_NAME"),
            "run_id": int(os.environ.get("GITHUB_RUN_ID", "0")),
            "run_attempt": int(os.environ.get("GITHUB_RUN_ATTEMPT", "0")),
            "runner_name": os.environ.get("RUNNER_NAME"),
            "runner_os": os.environ.get("RUNNER_OS"),
            "runner_arch": os.environ.get("RUNNER_ARCH"),
            "image_os": os.environ.get("ImageOS"),
            "image_version": os.environ.get("ImageVersion"),
            "status": "completed",
            "conclusion": "success",
            "science_state": science_state,
            "chunkshift_commit": CONSUMER_SHA,
            "chunkshift_cli_sha256": s4.file_sha256(cli),
            "rust_binary_sha256": s4.file_sha256(rust_binary),
        }
        write_json(out / "run.json", run_record)
        print(json.dumps({
            "repeat": args.repeat,
            "science_state": science_state,
            "quality_rows": len(rows),
            "parity_ok": parity_ok,
        }, sort_keys=True))
        return 0
    finally:
        shutil.rmtree(work, ignore_errors=True)


def parser():
    p = argparse.ArgumentParser()
    p.add_argument("plan")
    p.add_argument("store")
    p.add_argument("chunkshift_dll")
    p.add_argument("rust_binary")
    p.add_argument("out_dir")
    p.add_argument("--repeat", choices=("A", "B"), required=True)
    p.add_argument("--protocol-root", required=True)
    p.add_argument("--protocol-authority", required=True)
    p.add_argument("--implementation-sha", required=True)
    return p


if __name__ == "__main__":
    raise SystemExit(run(parser().parse_args()))
